name: Perform-minimum-validation-for-possible-breakpoints-in-tverplus-userscript-puppeteer

on:
  workflow_call:

jobs:
  validation-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Refer to https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
      # Refer to https://github.com/puppeteer/puppeteer/blob/312a65117036845241e1dcf792cd0101edbdf4cd/.github/workflows/ci.yml#L145
      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Setup Puppeteer
        run: npm i puppeteer

      - name: Run Puppeteer script to verify essential 'tver' elements are present and series data is properly injected via userscript
        run: node ./.github/workflows/tverplus_puppeteer.mjs
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REF: ${{ github.head_ref }}
