name: Perform-minimum-validation-for-possible-breakpoints-in-tverplus-userscript-puppeteer

on:
  workflow_call:

jobs:
  validation-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Puppeteer script to verify essential 'tver' elements are present and series data is properly injected via userscript
        uses: tj-actions/puppeteer@v5
        id: puppeteer
        with:
          files: |
            ./.github/workflows/tverplus_puppeteer.mjs
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REF: ${{ github.head_ref }}
